language: php
php:
- 5.6
- 7.1
sudo: false
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - resources/vendor
  - "$HOME/.composer/cache"
install:
- nvm install 8
- npm install
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- ls -la resources/style.css resources/index.php resources/vendor/autoload.php
- composer test
before_deploy:
- npm run zip
- ls -la snow-monkey.zip
- export RELEASE_FILE=$(ls snow-monkey.zip)
deploy:
  provider: releases
  api_key:
    secure: 6aVHLnx9lKcCnoPxEYUk70IFdrr4eUSPbURsxln/TZPvF4jqkHm2UrxXKgD/9F8nADBNDj9mLWuHufgXxI93hZp2s3xEl26DlBXTHYLEF/Tdx9aQOeKfH1VX6Nf4zE9bSpmwKNj+yo8LrgUUFiNG7H/V8FqkHGZVCfv4AcwucH//0SpnaoYfy5Mpp7zhYMJdDGs7w1pZFBzRidIN3NWytD1mskcC1YRpL7opZOevNowtX2B8MNKvxy71tWRO4HMxiTGLi9WUJAve7jBXN5tKjrJftAsy588Dbt75WPY6pdR51OnXcQwrPpaNQ/YVBiBv92Cudoz2l63kXfsYCyTxZBGX06A193ZjOz2u4F6Yd2c/Zi4OnSyMaCCowAVpgNote8aHrj1psjkwkZ8BwUKYpcqT00R2Jbr2+GxdetwRoZ2gLUt+I4lcmdZIVYYztbpNpoIOVZBwfNhdG5NVnAat24yCuQjLa263MfK6J2QtXKuIXZJdG7NqcpFcf4QvGsdbgaARj9ejRuCr9xkSsCPrDeHC5RXsu83bhm7YB+xNg5PDybj0Kcg75n3fqgeKO28QDkO4C+Gc93tDTW9AM2vU1BLQKFY//5pGhgL3rcn75BOjXdIM5TxGij0808lPuqURjf3c+n20b6KkTbSAEhDkHuYIRouJ4fCuEg7qX6NpQ8A=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: inc2734/snow-monkey
    php: 7.1
